/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package machinaproject;

import javax.swing.JOptionPane;


/**
 *
 * @author 
 */
public class Interfaz extends javax.swing.JFrame {

    private Control control;
    
    public Interfaz(Control control) {
        this.control = control;
        initComponents();
        machineRefresh();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }
    
    private void machineRefresh(){
        setNumExponente(control.getNumBitsPotencia());
        setNumMantisa(control.getNumBitsMantisa());
        setOverflow(control.getOverflow());
        setEpsilon(control.getEpsilon());
        setUnderflow(control.getUnderflow());
        
    }
    
    private void setNumExponente(int numExpo){
        this.numExponenteLabel.setText(String.format("Tiene %d bits para el exponente", numExpo));  
    }
    
    private void setNumMantisa(int numMant){
        this.numMantisaLabel.setText(String.format("Tiene %d bits para la mantisa", numMant));  
    }
    
    private void setOverflow(double overflow){
        this.overflowLabel.setText(String.format("Overflow: %g", overflow));
    }
    
    private void setEpsilon(double epsilon){
        this.epsilonLabel.setText(String.format("Epsilon: %g", epsilon));
    }
    
    private void setUnderflow(double underflow){
        this.underflowLabel.setText(String.format("Underflow: %g", underflow));
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectTitleLabel = new javax.swing.JLabel();
        descriptionTitleLabel = new javax.swing.JLabel();
        numExponenteLabel = new javax.swing.JLabel();
        numMantisaLabel = new javax.swing.JLabel();
        overflowLabel = new javax.swing.JLabel();
        epsilonLabel = new javax.swing.JLabel();
        underflowLabel = new javax.swing.JLabel();
        numBitsExpoField = new javax.swing.JTextField();
        expMChangeLabel = new javax.swing.JLabel();
        manMChangeLabel = new javax.swing.JLabel();
        numBitsMantField = new javax.swing.JTextField();
        changeMachinaButton = new javax.swing.JButton();
        real2MachineField = new javax.swing.JTextField();
        outputTitleLabel = new javax.swing.JLabel();
        real2MachineButton = new javax.swing.JButton();
        real2MachineOutputLabel = new javax.swing.JLabel();
        realNumberTitleLabel = new javax.swing.JLabel();
        MachineNumberTitleLabel = new javax.swing.JLabel();
        machine2RealField = new javax.swing.JTextField();
        machine2RealButton = new javax.swing.JButton();
        machine2RealOutputLabel = new javax.swing.JLabel();
        cleanButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        projectTitleLabel.setText("Título del Proyecto");

        descriptionTitleLabel.setText("Descripción de la máquina actual:");

        numExponenteLabel.setText("Tiene x bits para el exponente");

        numMantisaLabel.setText("Tiene x bits para la mantisa");

        overflowLabel.setText("Overflow: x");

        epsilonLabel.setText("Epsilon: x");

        underflowLabel.setText("Underflow: x");

        numBitsExpoField.setToolTipText("Ingrese un número entero entre 1 y 7");

        expMChangeLabel.setText("Número de bits para el exponente:");

        manMChangeLabel.setText("Número de bits para la mantisa:");

        numBitsMantField.setToolTipText("Ingrese un número entero entre 1 y 23");
        numBitsMantField.setMaximumSize(new java.awt.Dimension(2, 2147483647));

        changeMachinaButton.setText("Cambiar de máquina");
        changeMachinaButton.setToolTipText("");
        changeMachinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMachinaButtonActionPerformed(evt);
            }
        });

        outputTitleLabel.setText("Resultado:");

        real2MachineButton.setText("Cambiar número real a número máquina");
        real2MachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                real2MachineButtonActionPerformed(evt);
            }
        });

        realNumberTitleLabel.setText("Número real:");

        MachineNumberTitleLabel.setText("Número máquina:");

        machine2RealButton.setText("Cambiar número máquina a número real");
        machine2RealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machine2RealButtonActionPerformed(evt);
            }
        });

        machine2RealOutputLabel.setToolTipText("");

        cleanButton.setText("Limpiar");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Cerrar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(168, 168, 168)
                .addComponent(cleanButton)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(descriptionTitleLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numMantisaLabel)
                                            .addComponent(numExponenteLabel)
                                            .addComponent(overflowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(epsilonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(underflowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(expMChangeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(manMChangeLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numBitsExpoField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                            .addComponent(numBitsMantField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(changeMachinaButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(realNumberTitleLabel)
                                    .addComponent(MachineNumberTitleLabel))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(real2MachineButton)
                                        .addGap(44, 44, 44)
                                        .addComponent(real2MachineOutputLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(machine2RealButton)
                                        .addGap(44, 44, 44)
                                        .addComponent(machine2RealOutputLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(machine2RealField, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(real2MachineField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(62, 62, 62)
                                        .addComponent(outputTitleLabel))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(projectTitleLabel)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(projectTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTitleLabel)
                    .addComponent(numExponenteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numMantisaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overflowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(epsilonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underflowLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(expMChangeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(manMChangeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numBitsExpoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numBitsMantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(real2MachineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(realNumberTitleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(real2MachineButton)
                            .addComponent(real2MachineOutputLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(machine2RealField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MachineNumberTitleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(machine2RealButton)
                            .addComponent(machine2RealOutputLabel))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleanButton)
                            .addComponent(closeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeMachinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(outputTitleLabel)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeMachinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMachinaButtonActionPerformed
        try{
            control.updateMachine(numBitsExpoField.getText(), numBitsMantField.getText());
            machineRefresh();
        } catch(Exception e){
            String eMessage = e.getMessage();
            if(eMessage.equals("El número de bits del exponente debe ser un entero") 
                    || eMessage.equals("El número de bits del exponente debe estar entre 1 y 7")){
                this.numBitsExpoField.setText(null);              
            }
            if(eMessage.equals("El número de bits de la mantisa debe ser un entero") 
                    || eMessage.equals("El número de bits de la mantisa debe estar entre 1 y 23")){
                this.numBitsMantField.setText(null);              
            }
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_changeMachinaButtonActionPerformed

    private void real2MachineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_real2MachineButtonActionPerformed
        try{
            real2MachineOutputLabel.setText(control.real2Machine(real2MachineField.getText()));
        } catch(Exception e){
            this.real2MachineField.setText(null);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_real2MachineButtonActionPerformed

    private void machine2RealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machine2RealButtonActionPerformed
        try{
            machine2RealOutputLabel.setText(Double.toString(control.machine2Real(machine2RealField.getText())));
        } catch(Exception e){
            this.machine2RealField.setText(null);
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_machine2RealButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        this.numBitsExpoField.setText(null);
        this.numBitsMantField.setText(null);
        this.real2MachineField.setText(null);
        this.machine2RealField.setText(null);
        this.machine2RealOutputLabel.setText(null);
        this.real2MachineOutputLabel.setText(null);
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MachineNumberTitleLabel;
    private javax.swing.JButton changeMachinaButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel descriptionTitleLabel;
    private javax.swing.JLabel epsilonLabel;
    private javax.swing.JLabel expMChangeLabel;
    private javax.swing.JButton machine2RealButton;
    private javax.swing.JTextField machine2RealField;
    private javax.swing.JLabel machine2RealOutputLabel;
    private javax.swing.JLabel manMChangeLabel;
    private javax.swing.JTextField numBitsExpoField;
    private javax.swing.JTextField numBitsMantField;
    private javax.swing.JLabel numExponenteLabel;
    private javax.swing.JLabel numMantisaLabel;
    private javax.swing.JLabel outputTitleLabel;
    private javax.swing.JLabel overflowLabel;
    private javax.swing.JLabel projectTitleLabel;
    private javax.swing.JButton real2MachineButton;
    private javax.swing.JTextField real2MachineField;
    private javax.swing.JLabel real2MachineOutputLabel;
    private javax.swing.JLabel realNumberTitleLabel;
    private javax.swing.JLabel underflowLabel;
    // End of variables declaration//GEN-END:variables
}
